# Generated by Django 5.2.17 on 2026-08-11 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='original name')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB id')),
                ('wikidata_id', models.CharField(blank=True, max_length=32, verbose_name='Wikidata id')),
                ('photo_url', models.URLField(blank=True, verbose_name='photo URL')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='birth year')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='death year')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('original_title', models.CharField(blank=True, max_length=300, verbose_name='original title')),
                ('year', models.IntegerField(db_index=True, verbose_name='release year')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB id')),
                ('imdb_id', models.CharField(blank=True, max_length=16, verbose_name='IMDb id')),
                ('wikidata_id', models.CharField(blank=True, max_length=32, verbose_name='Wikidata id')),
                ('poster_url', models.URLField(blank=True, verbose_name='poster URL')),
                ('runtime', models.PositiveIntegerField(blank=True, null=True, verbose_name='runtime, min')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Whole numbers 1–10, empty = not watched yet.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rating')),
                ('watched_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='watched on')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('genres', models.ManyToManyField(blank=True, related_name='films', to='films.genre', verbose_name='genres')),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'films',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dir', 'Director'), ('act', 'Actor'), ('comp', 'Composer'), ('dop', 'Cinematographer'), ('writ', 'Writer')], max_length=4, verbose_name='role')),
                ('character', models.CharField(blank=True, max_length=200, verbose_name='character')),
                ('billing', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='billing order')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='films.film', verbose_name='film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='films.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'credit',
                'verbose_name_plural': 'credits',
                'ordering': ['billing', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.UniqueConstraint(fields=('title', 'year'), name='unique_film_title_year'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['person', 'role'], name='films_credi_person__016de7_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['role'], name='films_credi_role_13ba76_idx'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(fields=('film', 'person', 'role'), name='unique_credit'),
        ),
    ]
